"""Database migrations package (extracted from connection.py, iua3.7).

- pre: structural pre-migrations (renames/table rebuilds) — run before
  reconciliation + executescript
- versioned: schema_version-gated data migrations — run after executescript
"""

from apex.database.migrations.pre import (
    _migrate_detection_keywords_check,
    _migrate_exception_keywords_columns,
    _migrate_settings_for_v65,
    _migrate_stream_match_cache_check,
    _rename_league_id_column_if_needed,
    run_pre_migrations,
)
from apex.database.migrations.versioned import (
    _add_column_if_not_exists,
    _advance_version,
    _apply_migration,
    _column_exists,
    _dedup_cross_group_channels,
    _get_current_schema_version,
    _migrate_detection_keywords_restore_if_needed,
    _migrate_stream_match_cache_restore_if_needed,
    _migrate_v50_soccer_modes,
    _migrate_v53_api_defaults,
    _migrate_v58_sports_subscription,
    _migrate_v59_channel_numbering,
    _migrate_v61_subscription_league_config,
    _migrate_v62_default_channel_group,
    _migrate_v63_nullable_managed_channel_group,
    _migrate_v64_dedup_channels,
    _migrate_v65_lifecycle_timing_restore_if_needed,
    _migrate_v66_tsdb_tiers,
    _migrate_v67_remove_cricbuzz,
    _migrate_v69_feed_team_channels,
    _migrate_v72_split_xmltv_categories,
    _migrate_v73_dedupe_milb_renamed_codes,
    _migrate_v74_preserve_epg_match_offstate,
    _migrate_v75_extract_art_base_url,
    _migrate_v76_leading_slash_art_paths,
    _migrate_v78_strip_slash_before_art_variable,
    _recover_schema_version_from_v65_backup_if_needed,
    _run_migrations,
    _table_exists,
    _v73_remap_json_array,
)

__all__ = [
    "_add_column_if_not_exists",
    "_advance_version",
    "_apply_migration",
    "_column_exists",
    "_dedup_cross_group_channels",
    "_get_current_schema_version",
    "_migrate_detection_keywords_check",
    "_migrate_detection_keywords_restore_if_needed",
    "_migrate_exception_keywords_columns",
    "_migrate_settings_for_v65",
    "_migrate_stream_match_cache_check",
    "_migrate_stream_match_cache_restore_if_needed",
    "_migrate_v50_soccer_modes",
    "_migrate_v53_api_defaults",
    "_migrate_v58_sports_subscription",
    "_migrate_v59_channel_numbering",
    "_migrate_v61_subscription_league_config",
    "_migrate_v62_default_channel_group",
    "_migrate_v63_nullable_managed_channel_group",
    "_migrate_v64_dedup_channels",
    "_migrate_v65_lifecycle_timing_restore_if_needed",
    "_migrate_v66_tsdb_tiers",
    "_migrate_v67_remove_cricbuzz",
    "_migrate_v69_feed_team_channels",
    "_migrate_v72_split_xmltv_categories",
    "_migrate_v73_dedupe_milb_renamed_codes",
    "_migrate_v74_preserve_epg_match_offstate",
    "_migrate_v75_extract_art_base_url",
    "_migrate_v76_leading_slash_art_paths",
    "_migrate_v78_strip_slash_before_art_variable",
    "_recover_schema_version_from_v65_backup_if_needed",
    "_rename_league_id_column_if_needed",
    "_run_migrations",
    "_table_exists",
    "_v73_remap_json_array",
    "run_pre_migrations",
]
