"""Database operations for application settings.

Provides CRUD operations for the settings table (singleton row).
Settings are organized into logical groups for easier management.
"""

from .read import (
    get_all_settings,
    get_backup_settings,
    get_channel_numbering_settings,
    get_channelsdvr_settings,
    get_dispatcharr_settings,
    get_display_settings,
    get_emby_settings,
    get_epg_settings,
    get_feed_separation_settings,
    get_jellyfin_settings,
    get_lifecycle_settings,
    get_scheduler_settings,
    get_stream_filter_settings,
    get_stream_ordering_settings,
    get_team_filter_settings,
    get_update_check_settings,
)
from .types import (
    AllSettings,
    APISettings,
    BackupSettings,
    ChannelNumberingSettings,
    ChannelsDVRSettings,
    DispatcharrSettings,
    DisplaySettings,
    DurationSettings,
    EmbySettings,
    EPGSettings,
    FeedSeparationSettings,
    JellyfinSettings,
    LifecycleSettings,
    ReconciliationSettings,
    SchedulerSettings,
    StreamFilterSettings,
    StreamOrderingRule,
    StreamOrderingSettings,
    TeamFilterSettings,
    UpdateCheckSettings,
)
from .update import (
    increment_epg_generation_counter,
    update_backup_settings,
    update_channel_numbering_settings,
    update_channelsdvr_settings,
    update_dispatcharr_settings,
    update_display_settings,
    update_duration_settings,
    update_emby_settings,
    update_epg_settings,
    update_feed_separation_settings,
    update_jellyfin_settings,
    update_lifecycle_settings,
    update_reconciliation_settings,
    update_scheduler_settings,
    update_stream_ordering_rules,
    update_team_filter_settings,
    update_update_check_settings,
)

__all__ = [
    # Types
    "DispatcharrSettings",
    "ChannelsDVRSettings",
    "EmbySettings",
    "JellyfinSettings",
    "LifecycleSettings",
    "ReconciliationSettings",
    "SchedulerSettings",
    "EPGSettings",
    "DurationSettings",
    "DisplaySettings",
    "APISettings",
    "StreamFilterSettings",
    "StreamOrderingRule",
    "StreamOrderingSettings",
    "TeamFilterSettings",
    "ChannelNumberingSettings",
    "UpdateCheckSettings",
    "BackupSettings",
    "FeedSeparationSettings",
    "AllSettings",
    # Read operations
    "get_all_settings",
    "get_dispatcharr_settings",
    "get_channelsdvr_settings",
    "get_emby_settings",
    "get_jellyfin_settings",
    "get_scheduler_settings",
    "get_lifecycle_settings",
    "get_epg_settings",
    "get_display_settings",
    "get_stream_filter_settings",
    "get_stream_ordering_settings",
    "get_team_filter_settings",
    "get_channel_numbering_settings",
    "get_update_check_settings",
    "get_backup_settings",
    "get_feed_separation_settings",
    # Update operations
    "update_dispatcharr_settings",
    "update_channelsdvr_settings",
    "update_emby_settings",
    "update_jellyfin_settings",
    "update_scheduler_settings",
    "update_lifecycle_settings",
    "update_epg_settings",
    "update_reconciliation_settings",
    "update_duration_settings",
    "update_display_settings",
    "update_stream_ordering_rules",
    "update_team_filter_settings",
    "update_channel_numbering_settings",
    "update_update_check_settings",
    "update_backup_settings",
    "update_feed_separation_settings",
    "increment_epg_generation_counter",
]
